plugins {
    id 'com.android.application'
}

android {
    namespace 'com.homestay.app'
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
        versionCode 3
        versionName "1.0.2"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        applicationId "com.homestay.app"

        manifestPlaceholders = [
            appName: "Home Stay",
            hostName: "homestay-homestay7075-langs-projects.vercel.app",
            defaultUrl: "https://homestay-homestay7075-langs-projects.vercel.app/login",
            startUrl: "https://homestay-homestay7075-langs-projects.vercel.app/login",
            assetStatements: '[]'
        ]
    }

    signingConfigs {
        release {
            if (file("${projectDir}/debug.keystore").exists()) {
                storeFile file("${projectDir}/debug.keystore")
            } else if (file("debug.keystore").exists()) {
                storeFile file("debug.keystore")
            } else if (file("C:/Users/laksh/.android/debug.keystore").exists()) {
                storeFile file("C:/Users/laksh/.android/debug.keystore")
            } else {
                storeFile file("${projectDir}/debug.keystore")
            }
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.release
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
